server:
  port: 8080

spring:
  application:
    name: customer-service

  redis:
    host: localhost
    port: 6379

  elasticsearch:
    uris: http://localhost:9200

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.multica.customer: DEBUG
